# Generated by Django 3.0.8 on 2020-07-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('fullname', models.CharField(max_length=20)),
                ('account_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('balance', models.BigIntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('transaction_type', models.IntegerField(choices=[(0, 'debit'), (1, 'credit')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'accepted'), (1, 'declined')], default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.AccountDetails')),
            ],
        ),
    ]
